// Date: 2/7/2013 3:12:36 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package rivendark.mods.quantumassembly.machines;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelQuantumStorageExtender extends ModelBase
{
  //fields
    ModelRenderer Back;
    ModelRenderer Container;
    ModelRenderer LeftSupport;
    ModelRenderer RightSupport;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape6;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
  
  public ModelQuantumStorageExtender()
  {
    textureWidth = 64;
    textureHeight = 128;
    
      Back.mirror = true;
      Back = new ModelRenderer(this, 0, 66);
      Back.addBox(-8F, -14F, 6F, 16, 16, 2);
      Back.setRotationPoint(0F, 22F, 0F);
      Back.setTextureSize(64, 32);
      Back.mirror = true;
      setRotation(Back, 0F, 0F, 0F);
      Back.mirror = false;
      Container = new ModelRenderer(this, 0, 37);
      Container.addBox(-6F, -15F, -6F, 12, 16, 12);
      Container.setRotationPoint(0F, 23F, 0F);
      Container.setTextureSize(64, 32);
      Container.mirror = true;
      setRotation(Container, 0F, 0F, 0F);
      LeftSupport = new ModelRenderer(this, 49, 37);
      LeftSupport.addBox(-8F, -15F, -8F, 1, 15, 1);
      LeftSupport.setRotationPoint(0F, 23F, 0F);
      LeftSupport.setTextureSize(64, 32);
      LeftSupport.mirror = true;
      setRotation(LeftSupport, 0F, 0F, 0F);
      RightSupport = new ModelRenderer(this, 49, 37);
      RightSupport.addBox(7F, -15F, -8F, 1, 15, 1);
      RightSupport.setRotationPoint(0F, 23F, 0F);
      RightSupport.setTextureSize(64, 32);
      RightSupport.mirror = true;
      setRotation(RightSupport, 0F, 0F, 0F);
      Shape1.mirror = true;
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(-8F, 0F, -8F, 1, 1, 14);
      Shape1.setRotationPoint(0F, 23F, 0F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape1.mirror = false;
      Shape2 = new ModelRenderer(this, 0, 0);
      Shape2.addBox(7F, 0F, -8F, 1, 1, 14);
      Shape2.setRotationPoint(0F, 23F, 0F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 19);
      Shape3.addBox(-7F, -15F, -8F, 14, 1, 1);
      Shape3.setRotationPoint(0F, 23F, 0F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape3.mirror = true;
      Shape6 = new ModelRenderer(this, 0, 16);
      Shape6.addBox(-7F, 0F, -8F, 14, 1, 1);
      Shape6.setRotationPoint(0F, 23F, 0F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape6.mirror = false;
      Shape4 = new ModelRenderer(this, 0, 22);
      Shape4.addBox(-8F, -15F, -7F, 1, 1, 13);
      Shape4.setRotationPoint(0F, 23F, 0F);
      Shape4.setTextureSize(64, 128);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 22);
      Shape5.addBox(7F, -15F, -7F, 1, 1, 13);
      Shape5.setRotationPoint(0F, 23F, 0F);
      Shape5.setTextureSize(64, 128);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Back.render(f5);
    Container.render(f5);
    LeftSupport.render(f5);
    RightSupport.render(f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
  }
  
  public void renderModel(float f5)
  {
    Back.render(f5);
    Container.render(f5);
    LeftSupport.render(f5);
    RightSupport.render(f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
