// Date: 2/4/2013 12:50:51 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package rivendark.mods.quantumassembly.machines;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class QuantumStorageModel extends ModelBase
{
  //fields
    ModelRenderer Bottom;
    ModelRenderer Back;
    ModelRenderer Chest;
    ModelRenderer Top;
    ModelRenderer LeftPole;
    ModelRenderer RightPole;
  
  public QuantumStorageModel()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Bottom = new ModelRenderer(this, 64, 0);
      Bottom.addBox(-8F, 0F, -8F, 16, 1, 16);
      Bottom.setRotationPoint(0F, 23F, 0F);
      Bottom.setTextureSize(128, 64);
      Bottom.mirror = true;
      setRotation(Bottom, 0F, -1.570796F, 0F);
      Back = new ModelRenderer(this, 90, 17);
      Back.addBox(5F, -8F, -8F, 3, 12, 16);
      Back.setRotationPoint(0F, 19F, 0F);
      Back.setTextureSize(128, 64);
      Back.mirror = true;
      setRotation(Back, 0F, -1.570796F, 0F);
      Chest = new ModelRenderer(this, 0, 19);
      Chest.addBox(-6F, 11F, -6F, 11, 12, 12);
      Chest.setRotationPoint(0F, 0F, 0F);
      Chest.setTextureSize(128, 64);
      Chest.mirror = true;
      setRotation(Chest, 0F, -1.570796F, 0F);
      Top = new ModelRenderer(this, 0, 0);
      Top.addBox(-8F, 8F, -8F, 16, 3, 16);
      Top.setRotationPoint(0F, 0F, 0F);
      Top.setTextureSize(128, 64);
      Top.mirror = true;
      setRotation(Top, 0F, -1.570796F, 0F);
      LeftPole = new ModelRenderer(this, 48, 24);
      LeftPole.addBox(-8F, 11F, 7F, 1, 12, 1);
      LeftPole.setRotationPoint(0F, 0F, 0F);
      LeftPole.setTextureSize(128, 64);
      LeftPole.mirror = true;
      setRotation(LeftPole, 0F, -1.570796F, 0F);
      RightPole = new ModelRenderer(this, 48, 24);
      RightPole.addBox(-8F, 11F, -8F, 1, 12, 1);
      RightPole.setRotationPoint(0F, 0F, 0F);
      RightPole.setTextureSize(128, 64);
      RightPole.mirror = true;
      setRotation(RightPole, 0F, -1.570796F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Bottom.render(f5);
    Back.render(f5);
    Chest.render(f5);
    Top.render(f5);
    LeftPole.render(f5);
    RightPole.render(f5);
  }
  
  public void renderModel(float f5){
	  	Bottom.render(f5);
	  	Back.render(f5);
	 	Chest.render(f5);
	    Top.render(f5);
	    LeftPole.render(f5);
	    RightPole.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
